/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ../../assets/3d-models/PinkForest.glb -T
Author: Whitend (https://sketchfab.com/whitend.3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shiny-forest-a36f80984fc24bd8919cb10bc3cc3fa4
Title: Shiny Forest
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
import PinkForestModel from '../assets/PinkForest.glb';

const PinkForest = (props) => {
  const { nodes, materials } = useGLTF(PinkForestModel);
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.33}>
        <mesh
          geometry={nodes.Plane001_0.geometry}
          material={materials.Ground}
          scale={27.2}
        />
        <mesh
          geometry={nodes.tree000_0.geometry}
          material={materials['tree.012_0']}
          position={[-13.58, 2.89, 0.97]}
          rotation={[-0.07, -0.25, Math.PI]}
          scale={1.37}
        />
        <mesh
          geometry={nodes.BlueFlowers3805_0.geometry}
          material={materials.BlueFlowers}
          position={[-13.58, 2.89, 0.97]}
          rotation={[1.83, -0.96, 2.51]}
          scale={[0.38, 0.76, 0.59]}
        />
        <mesh
          geometry={nodes.tree002_0.geometry}
          material={materials['tree.012_0']}
          position={[-7.45, -6.32, 2.97]}
          rotation={[0.12, -0.28, Math.PI]}
          scale={1.46}
        />
        <mesh
          geometry={nodes.BlueFlowers3806_0.geometry}
          material={materials.BlueFlowers}
          position={[-7.45, -6.32, 2.97]}
          rotation={[2.07, -0.95, 2.58]}
          scale={[0.41, 0.81, 0.63]}
        />
        <mesh
          geometry={nodes.tree003_0.geometry}
          material={materials['tree.012_0']}
          position={[-6.46, 6.14, 2.54]}
          rotation={[-0.06, -0.2, -Math.PI]}
          scale={0.84}
        />
        <mesh
          geometry={nodes.BlueFlowers3807_0.geometry}
          material={materials.BlueFlowers}
          position={[-6.46, 6.14, 2.54]}
          rotation={[1.76, -0.98, 2.43]}
          scale={[0.24, 0.47, 0.37]}
        />
        <mesh
          geometry={nodes.tree004_0.geometry}
          material={materials['tree.012_0']}
          position={[-1.48, 9.97, 2.66]}
          rotation={[-0.02, 0.12, Math.PI]}
          scale={0.7}
        />
        <mesh
          geometry={nodes.BlueFlowers3808_0.geometry}
          material={materials.BlueFlowers}
          position={[-1.48, 9.97, 2.66]}
          rotation={[1.33, -0.98, 1.86]}
          scale={[0.2, 0.39, 0.3]}
        />
        <mesh
          geometry={nodes.tree005_0.geometry}
          material={materials['tree.012_0']}
          position={[0.66, 9.16, 2.5]}
          rotation={[-0.15, 0.11, Math.PI]}
          scale={0.84}
        />
        <mesh
          geometry={nodes.BlueFlowers3809_0.geometry}
          material={materials.BlueFlowers}
          position={[0.66, 9.16, 2.5]}
          rotation={[1.21, -0.99, 1.88]}
          scale={[0.23, 0.46, 0.36]}
        />
        <mesh
          geometry={nodes.tree006_0.geometry}
          material={materials['tree.012_0']}
          position={[3.87, -4.55, 4.54]}
          rotation={[0.09, 0.11, -Math.PI]}
          scale={1.39}
        />
        <mesh
          geometry={nodes.BlueFlowers3810_0.geometry}
          material={materials.BlueFlowers}
          position={[3.87, -4.55, 4.54]}
          rotation={[1.45, -0.99, 1.88]}
          scale={[0.39, 0.77, 0.6]}
        />
        <mesh
          geometry={nodes.tree007_0.geometry}
          material={materials['tree.012_0']}
          position={[3.75, 8.46, 2.32]}
          rotation={[-0.27, 0.1, -Math.PI]}
          scale={1.28}
        />
        <mesh
          geometry={nodes.BlueFlowers3811_0.geometry}
          material={materials.BlueFlowers}
          position={[3.75, 8.46, 2.32]}
          rotation={[1.1, -0.99, 1.88]}
          scale={[0.36, 0.71, 0.55]}
        />
        <mesh
          geometry={nodes.tree008_0.geometry}
          material={materials['tree.012_0']}
          position={[4.7, 2.6, 3.85]}
          rotation={[-0.2, 0.15, Math.PI]}
          scale={1.22}
        />
        <mesh
          geometry={nodes.BlueFlowers3812_0.geometry}
          material={materials.BlueFlowers}
          position={[4.7, 2.6, 3.85]}
          rotation={[1.11, -0.98, 1.8]}
          scale={[0.34, 0.67, 0.53]}
        />
        <mesh
          geometry={nodes.tree009_0.geometry}
          material={materials['tree.012_0']}
          position={[6.42, -6.41, 3.91]}
          rotation={[0.17, 0.16, Math.PI]}
          scale={1.57}
        />
        <mesh
          geometry={nodes.BlueFlowers3813_0.geometry}
          material={materials.BlueFlowers}
          position={[6.42, -6.41, 3.91]}
          rotation={[1.46, -0.97, 1.78]}
          scale={[0.44, 0.87, 0.68]}
        />
        <mesh
          geometry={nodes.tree010_0.geometry}
          material={materials['tree.012_0']}
          position={[7.43, 11.88, 1.55]}
          rotation={[-0.08, -0.04, -Math.PI]}
          scale={1.08}
        />
        <mesh
          geometry={nodes.BlueFlowers3814_0.geometry}
          material={materials.BlueFlowers}
          position={[7.43, 11.88, 1.55]}
          rotation={[1.52, -1, 2.15]}
          scale={[0.3, 0.6, 0.47]}
        />
        <mesh
          geometry={nodes.tree011_0.geometry}
          material={materials['tree.012_0']}
          position={[10.22, -7.54, 3.01]}
          rotation={[0.2, 0.18, Math.PI]}
          scale={0.92}
        />
        <mesh
          geometry={nodes.BlueFlowers3815_0.geometry}
          material={materials.BlueFlowers}
          position={[10.22, -7.54, 3.01]}
          rotation={[1.46, -0.97, 1.75]}
          scale={[0.26, 0.51, 0.4]}
        />
        <mesh
          geometry={nodes.tree012_0.geometry}
          material={materials['tree.012_0']}
          position={[10.13, -1.59, 3.57]}
          rotation={[-0.13, 0.2, Math.PI]}
          scale={1.44}
        />
        <mesh
          geometry={nodes.BlueFlowers3816_0.geometry}
          material={materials.BlueFlowers}
          position={[10.13, -1.59, 3.57]}
          rotation={[1.11, -0.96, 1.72]}
          scale={[0.4, 0.8, 0.62]}
        />
      </group>
    </group>
  );
};

useGLTF.preload(PinkForestModel);
export default PinkForest;
