/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/Blackhole.glb -T
Author: shikoooooooo (https://sketchfab.com/shikoooooooo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/blackhole-32f978d0e7354af293fa498f2998b14c
Title: Blackhole
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

const Blackhole = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/Blackhole.glb');
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    actions['CINEMA_4D_Main'].play();
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="dcaa5659b3224679ba61a4e0f55630b4fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Blackhole">
                  <group
                    name="Lathe_S"
                    position={[0, 12.89, 0]}
                    rotation={[0, -0.96, 0]}>
                    <mesh
                      name="Lathe_S_Blackhole_01_0"
                      geometry={nodes.Lathe_S_Blackhole_01_0.geometry}
                      material={materials.Blackhole_01}
                    />
                  </group>
                  <group
                    name="Lathe_M"
                    position={[0, 5.52, 0]}
                    rotation={[0, -0.48, 0]}>
                    <mesh
                      name="Lathe_M_Blackhole_02_0"
                      geometry={nodes.Lathe_M_Blackhole_02_0.geometry}
                      material={materials.Blackhole_01}
                    />
                  </group>
                  <group name="Lathe_L" rotation={[0, -0.32, 0]}>
                    <mesh
                      name="Lathe_L_Blackhole_03_0"
                      geometry={nodes.Lathe_L_Blackhole_03_0.geometry}
                      material={materials.Blackhole_03}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload('/Blackhole.glb');
export default Blackhole;
