/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ../../assets/3d-models/Flower.glb -T
Author: buresin.eduard (https://sketchfab.com/buresin.eduard)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/flower-day-7-3december2022challenge-e8e12fcb2a8d447397ba18dfbd751905
Title: Flower Day 7 #3December2022Challenge
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
import FlowerModel from '../assets/Flower.glb';

const Flower = (props) => {
  const { nodes, materials } = useGLTF(FlowerModel);
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.56}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            userData={props.userData}
            geometry={nodes.Flower_Flower_0.geometry}
            material={materials.Flower}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
    </group>
  );
};

useGLTF.preload(FlowerModel);
export default Flower;
