/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ../../assets/3d-models/TreeHouses.glb -T
Author: alurisnow (https://sketchfab.com/alurisnow)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tree-houses-6089ea8ee3f94b0f84eeed6ff6cb4b92
Title: Tree houses
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
import TreeHousesModel from '../assets/TreeHouses.glb';

const TreeHouses = (props) => {
  const { nodes, materials } = useGLTF(TreeHousesModel);
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.62}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.pSphere46_OrganicTextures_0.geometry}
            material={materials.OrganicTextures}
          />
          <mesh
            geometry={nodes.pSphere46_Leaves_edges_0.geometry}
            material={materials.Leaves_edges}
          />
          <mesh
            geometry={nodes.pCube187_door_and_others_0.geometry}
            material={materials.door_and_others}
          />
          <mesh
            geometry={nodes.pCube187_chimney_and_others_0.geometry}
            material={materials.chimney_and_others}
          />
          <mesh
            geometry={nodes.WoodenSupport23_Platform_Stairs_0.geometry}
            material={materials.Platform_Stairs}
          />
          <mesh
            geometry={nodes.pPlane60_Leaves_edges_0.geometry}
            material={materials.Leaves_edges}
          />
          <mesh
            geometry={nodes.pPlane60_OrganicTextures_0.geometry}
            material={materials.OrganicTextures}
          />
          <mesh
            geometry={nodes.Leaf16_Leaves_edges_0.geometry}
            material={materials.Leaves_edges}
          />
          <mesh
            geometry={nodes.Leaf23_Leaves_edges_0.geometry}
            material={materials.Leaves_edges}
          />
          <mesh
            geometry={nodes.pPlane59_Leaves_edges_0.geometry}
            material={materials.Leaves_edges}
          />
          <mesh
            geometry={nodes.pPlane59_OrganicTextures_0.geometry}
            material={materials.OrganicTextures}
          />
          <mesh
            geometry={nodes.Leaf29_Leaves_edges_0.geometry}
            material={materials.Leaves_edges}
            position={[16.13, -0.25, 5.32]}
            rotation={[0, -0.33, 0]}
            scale={0.89}
          />
          <mesh
            geometry={nodes.Leaf21_Leaves_edges_0.geometry}
            material={materials.Leaves_edges}
          />
          <mesh
            geometry={nodes.pCube189_door_and_others_0.geometry}
            material={materials.door_and_others}
          />
          <mesh
            geometry={nodes.pCube189_chimney_and_others_0.geometry}
            material={materials.chimney_and_others}
          />
          <mesh
            geometry={nodes.pCube192_door_and_others_0.geometry}
            material={materials.door_and_others}
          />
          <mesh
            geometry={nodes.pCube192_chimney_and_others_0.geometry}
            material={materials.chimney_and_others}
          />
          <mesh
            geometry={nodes.Leaf24_Leaves_edges_0.geometry}
            material={materials.Leaves_edges}
          />
          <mesh
            geometry={nodes.pSphere47_OrganicTextures_0.geometry}
            material={materials.OrganicTextures}
          />
          <mesh
            geometry={nodes.pSphere47_Leaves_edges_0.geometry}
            material={materials.Leaves_edges}
          />
          <mesh
            geometry={nodes.Leaf14_Leaves_edges_0.geometry}
            material={materials.Leaves_edges}
          />
          <mesh
            geometry={nodes.pCube82_chimney_and_others_0.geometry}
            material={materials.chimney_and_others}
          />
          <mesh
            geometry={nodes.Platform58_Platform_Stairs_0.geometry}
            material={materials.Platform_Stairs}
          />
          <mesh
            geometry={nodes.Platform58_door_and_others_0.geometry}
            material={materials.door_and_others}
          />
          <mesh
            geometry={nodes.Platform58_chimney_and_others_0.geometry}
            material={materials.chimney_and_others}
          />
          <mesh
            geometry={nodes.pSphere45_OrganicTextures_0.geometry}
            material={materials.OrganicTextures}
          />
          <mesh
            geometry={nodes.pSphere45_Leaves_edges_0.geometry}
            material={materials.Leaves_edges}
          />
          <mesh
            geometry={nodes.pCylinder26_door_and_others_0.geometry}
            material={materials.door_and_others}
          />
          <mesh
            geometry={nodes.pCylinder26_windows_0.geometry}
            material={materials.windows}
          />
          <mesh
            geometry={nodes.pCylinder26_windows_Emission_0.geometry}
            material={materials.windows_Emission}
          />
          <mesh
            geometry={nodes.pCylinder26_chimney_and_others_0.geometry}
            material={materials.chimney_and_others}
          />
          <mesh
            geometry={nodes.pCylinder26_Roof02_0.geometry}
            material={materials.Roof02}
          />
          <mesh
            geometry={nodes.pCylinder26_Roof03_0.geometry}
            material={materials.Roof03}
          />
          <mesh
            geometry={nodes.Leaf30_Leaves_edges_0.geometry}
            material={materials.Leaves_edges}
            position={[19.78, 0.2, -4.95]}
          />
          <mesh
            geometry={nodes.pCube193_door_and_others_0.geometry}
            material={materials.door_and_others}
          />
          <mesh
            geometry={nodes.pCube193_chimney_and_others_0.geometry}
            material={materials.chimney_and_others}
          />
          <mesh
            geometry={nodes.pCube98_chimney_and_others_0.geometry}
            material={materials.chimney_and_others}
          />
          <mesh
            geometry={nodes.Leaf32_Leaves_edges_0.geometry}
            material={materials.Leaves_edges}
            position={[23.78, 0.19, -5.29]}
          />
          <mesh
            geometry={nodes.Branch06_OrganicTextures_0.geometry}
            material={materials.OrganicTextures}
          />
          <mesh
            geometry={nodes.Leaf20_Leaves_edges_0.geometry}
            material={materials.Leaves_edges}
          />
          <mesh
            geometry={nodes.pCube99_chimney_and_others_0.geometry}
            material={materials.chimney_and_others}
          />
          <mesh
            geometry={nodes.Leaf5_Leaves_edges_0.geometry}
            material={materials.Leaves_edges}
          />
          <mesh
            geometry={nodes.pCube190_door_and_others_0.geometry}
            material={materials.door_and_others}
          />
          <mesh
            geometry={nodes.pCube190_chimney_and_others_0.geometry}
            material={materials.chimney_and_others}
          />
          <mesh
            geometry={nodes.Ground33_OrganicTextures_0.geometry}
            material={materials.OrganicTextures}
          />
          <mesh
            geometry={nodes.Ground33_Leaves_edges_0.geometry}
            material={materials.Leaves_edges}
          />
          <mesh
            geometry={nodes.Leaf31_Leaves_edges_0.geometry}
            material={materials.Leaves_edges}
            position={[31.14, -0.5, -12.17]}
          />
          <mesh
            geometry={nodes.WoodenSupport24_Platform_Stairs_0.geometry}
            material={materials.Platform_Stairs}
          />
          <mesh
            geometry={nodes.Leaf22_Leaves_edges_0.geometry}
            material={materials.Leaves_edges}
          />
          <mesh
            geometry={nodes.Leaf25_Leaves_edges_0.geometry}
            material={materials.Leaves_edges}
          />
          <mesh
            geometry={nodes.pCylinder28_door_and_others_0.geometry}
            material={materials.door_and_others}
          />
          <mesh
            geometry={nodes.pCylinder28_windows_0.geometry}
            material={materials.windows}
          />
          <mesh
            geometry={nodes.pCylinder28_windows_Emission_0.geometry}
            material={materials.windows_Emission}
          />
          <mesh
            geometry={nodes.pCylinder28_chimney_and_others_0.geometry}
            material={materials.chimney_and_others}
          />
          <mesh
            geometry={nodes.pCylinder28_Roof02_0.geometry}
            material={materials.Roof02}
          />
          <mesh
            geometry={nodes.pCylinder28_Roof03_0.geometry}
            material={materials.Roof03}
          />
          <mesh
            geometry={nodes.pCylinder23_door_and_others_0.geometry}
            material={materials.door_and_others}
          />
          <mesh
            geometry={nodes.pCylinder23_windows_0.geometry}
            material={materials.windows}
          />
          <mesh
            geometry={nodes.pCylinder23_windows_Emission_0.geometry}
            material={materials.windows_Emission}
          />
          <mesh
            geometry={nodes.pCylinder23_chimney_and_others_0.geometry}
            material={materials.chimney_and_others}
          />
          <mesh
            geometry={nodes.pCylinder23_Roof02_0.geometry}
            material={materials.Roof02}
          />
          <mesh
            geometry={nodes.pCylinder23_Roof03_0.geometry}
            material={materials.Roof03}
          />
          <mesh
            geometry={nodes.pSphere34_OrganicTextures_0.geometry}
            material={materials.OrganicTextures}
          />
          <mesh
            geometry={nodes.pSphere34_Leaves_edges_0.geometry}
            material={materials.Leaves_edges}
          />
          <mesh
            geometry={nodes.pCube191_door_and_others_0.geometry}
            material={materials.door_and_others}
          />
          <mesh
            geometry={nodes.pCube191_chimney_and_others_0.geometry}
            material={materials.chimney_and_others}
          />
          <mesh
            geometry={nodes.Leaf26_Leaves_edges_0.geometry}
            material={materials.Leaves_edges}
            position={[19.85, -0.1, 0]}
          />
          <mesh
            geometry={nodes.Leaf27_Leaves_edges_0.geometry}
            material={materials.Leaves_edges}
            position={[19.85, -0.21, 0]}
          />
          <mesh
            geometry={nodes.WoodenSupport18_Platform_Stairs_0.geometry}
            material={materials.Platform_Stairs}
          />
          <mesh
            geometry={nodes.Leaf28_Leaves_edges_0.geometry}
            material={materials.Leaves_edges}
            position={[20.63, 0.49, -1.08]}
          />
          <mesh
            geometry={nodes.pSphere33_OrganicTextures_0.geometry}
            material={materials.OrganicTextures}
          />
          <mesh
            geometry={nodes.pSphere33_Leaves_edges_0.geometry}
            material={materials.Leaves_edges}
          />
          <mesh
            geometry={nodes.pSphere39_OrganicTextures_0.geometry}
            material={materials.OrganicTextures}
          />
          <mesh
            geometry={nodes.pSphere39_Leaves_edges_0.geometry}
            material={materials.Leaves_edges}
          />
          <mesh
            geometry={nodes.Branch05_OrganicTextures_0.geometry}
            material={materials.OrganicTextures}
          />
          <mesh
            geometry={nodes.pSphere32_OrganicTextures_0.geometry}
            material={materials.OrganicTextures}
          />
          <mesh
            geometry={nodes.pSphere32_Leaves_edges_0.geometry}
            material={materials.Leaves_edges}
          />
          <mesh
            geometry={nodes.Leaf9_Leaves_edges_0.geometry}
            material={materials.Leaves_edges}
          />
          <mesh
            geometry={nodes.pSphere37_OrganicTextures_0.geometry}
            material={materials.OrganicTextures}
          />
          <mesh
            geometry={nodes.pSphere37_Leaves_edges_0.geometry}
            material={materials.Leaves_edges}
          />
          <mesh
            geometry={nodes.Leaf6_Leaves_edges_0.geometry}
            material={materials.Leaves_edges}
          />
          <mesh
            geometry={nodes.Leaf13_Leaves_edges_0.geometry}
            material={materials.Leaves_edges}
          />
          <mesh
            geometry={nodes.pCube51_chimney_and_others_0.geometry}
            material={materials.chimney_and_others}
          />
          <mesh
            geometry={nodes.Leaf11_Leaves_edges_0.geometry}
            material={materials.Leaves_edges}
          />
          <mesh
            geometry={nodes.Leaf12_Leaves_edges_0.geometry}
            material={materials.Leaves_edges}
          />
          <mesh
            geometry={nodes.pCylinder21_door_and_others_0.geometry}
            material={materials.door_and_others}
          />
          <mesh
            geometry={nodes.pCylinder21_windows_0.geometry}
            material={materials.windows}
          />
          <mesh
            geometry={nodes.pCylinder21_windows_Emission_0.geometry}
            material={materials.windows_Emission}
          />
          <mesh
            geometry={nodes.pCylinder21_chimney_and_others_0.geometry}
            material={materials.chimney_and_others}
          />
          <mesh
            geometry={nodes.pCylinder21_Roof02_0.geometry}
            material={materials.Roof02}
          />
          <mesh
            geometry={nodes.pCylinder21_Roof03_0.geometry}
            material={materials.Roof03}
          />
          <mesh
            geometry={nodes.Leaf15_Leaves_edges_0.geometry}
            material={materials.Leaves_edges}
          />
          <mesh
            geometry={nodes.pCylinder22_door_and_others_0.geometry}
            material={materials.door_and_others}
          />
          <mesh
            geometry={nodes.pCylinder22_windows_0.geometry}
            material={materials.windows}
          />
          <mesh
            geometry={nodes.pCylinder22_windows_Emission_0.geometry}
            material={materials.windows_Emission}
          />
          <mesh
            geometry={nodes.pCylinder22_chimney_and_others_0.geometry}
            material={materials.chimney_and_others}
          />
          <mesh
            geometry={nodes.pCylinder22_Roof02_0.geometry}
            material={materials.Roof02}
          />
          <mesh
            geometry={nodes.pCylinder22_Roof03_0.geometry}
            material={materials.Roof03}
          />
          <mesh
            geometry={nodes.Branch07_OrganicTextures_0.geometry}
            material={materials.OrganicTextures}
          />
          <mesh
            geometry={nodes.Branch07_Leaves_edges_0.geometry}
            material={materials.Leaves_edges}
          />
          <mesh
            geometry={nodes.pSphere38_OrganicTextures_0.geometry}
            material={materials.OrganicTextures}
          />
          <mesh
            geometry={nodes.pSphere38_Leaves_edges_0.geometry}
            material={materials.Leaves_edges}
          />
          <mesh
            geometry={nodes.pCylinder27_door_and_others_0.geometry}
            material={materials.door_and_others}
          />
          <mesh
            geometry={nodes.pCylinder27_windows_0.geometry}
            material={materials.windows}
          />
          <mesh
            geometry={nodes.pCylinder27_windows_Emission_0.geometry}
            material={materials.windows_Emission}
          />
          <mesh
            geometry={nodes.pCylinder27_chimney_and_others_0.geometry}
            material={materials.chimney_and_others}
          />
          <mesh
            geometry={nodes.pCylinder27_Roof02_0.geometry}
            material={materials.Roof02}
          />
          <mesh
            geometry={nodes.pCylinder27_Roof03_0.geometry}
            material={materials.Roof03}
          />
          <mesh
            geometry={nodes.pSphere48_blinn1_0.geometry}
            material={materials.blinn1}
            position={[3.1, 14.25, 3.76]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere49_blinn1_0.geometry}
            material={materials.blinn1}
            position={[2.77, 14.95, 3.19]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere50_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-2.34, 18.21, -4.93]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere51_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-2.01, 17.51, -4.36]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere52_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-2.34, 17.72, -4.88]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere53_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-0.29, 18.71, -5.49]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere58_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-6.31, 0, 3.7]}
            rotation={[0, -0.86, 0]}
          />
          <mesh
            geometry={nodes.pSphere59_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-6.31, 0, 3.7]}
            rotation={[0, -0.86, 0]}
          />
          <mesh
            geometry={nodes.pSphere60_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-0.29, 18.71, -5.49]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere61_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-2.34, 17.72, -4.88]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere62_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-2.01, 17.51, -4.36]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere63_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-2.34, 18.21, -4.93]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere64_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-12.02, 0, -2.8]}
            rotation={[0, -0.86, 0]}
          />
          <mesh
            geometry={nodes.pSphere65_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-6.01, 18.71, -11.99]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere66_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-8.06, 17.72, -11.38]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere67_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-7.72, 17.51, -10.86]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere68_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-8.06, 18.21, -11.43]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere69_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-10.51, 1.48, 3.31]}
            rotation={[-0.26, -0.24, -0.33]}
          />
          <mesh
            geometry={nodes.pSphere70_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-5.95, 0.82, 2.4]}
            rotation={[0, 0.51, -0.36]}
          />
          <mesh
            geometry={nodes.pSphere71_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-1.09, -0.13, 7.07]}
            rotation={[-0.43, -0.64, -0.4]}
          />
          <mesh
            geometry={nodes.pSphere72_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-5.58, 0.12, 5.89]}
            rotation={[-1.44, -1.24, -1.27]}
          />
          <mesh
            geometry={nodes.pSphere73_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-0.38, -1.92, 5.17]}
            rotation={[-Math.PI, -1.06, -Math.PI]}
          />
          <mesh
            geometry={nodes.pSphere74_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-0.38, -1.92, 5.17]}
            rotation={[-Math.PI, -1.06, -Math.PI]}
          />
          <mesh
            geometry={nodes.pSphere75_blinn1_0.geometry}
            material={materials.blinn1}
            position={[4.99, 16.28, -1.07]}
            rotation={[0, -1.22, 0]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere76_blinn1_0.geometry}
            material={materials.blinn1}
            position={[5.32, 15.58, -0.5]}
            rotation={[0, -1.22, 0]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere77_blinn1_0.geometry}
            material={materials.blinn1}
            position={[4.99, 15.8, -1.02]}
            rotation={[0, -1.22, 0]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere78_blinn1_0.geometry}
            material={materials.blinn1}
            position={[7.04, 16.78, -1.63]}
            rotation={[0, -1.22, 0]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere79_blinn1_0.geometry}
            material={materials.blinn1}
            position={[7.04, 16.78, -1.63]}
            rotation={[0, -1.22, 0]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere80_blinn1_0.geometry}
            material={materials.blinn1}
            position={[4.99, 15.8, -1.02]}
            rotation={[0, -1.22, 0]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere81_blinn1_0.geometry}
            material={materials.blinn1}
            position={[5.32, 15.58, -0.5]}
            rotation={[0, -1.22, 0]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere82_blinn1_0.geometry}
            material={materials.blinn1}
            position={[4.99, 16.28, -1.07]}
            rotation={[0, -1.22, 0]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere83_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-12.14, 13.5, 14.8]}
            rotation={[0, 0.51, -1.55]}
          />
          <mesh
            geometry={nodes.pSphere84_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-18.5, 12.34, 2.61]}
            rotation={[-0.26, -0.24, -1.51]}
          />
          <mesh
            geometry={nodes.pSphere85_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-12.83, 7.16, -3.22]}
            rotation={[0, -0.86, -1.19]}
          />
          <mesh
            geometry={nodes.pSphere86_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-12.83, 7.16, -3.22]}
            rotation={[0, -0.86, -1.19]}
          />
          <mesh
            geometry={nodes.pSphere87_blinn1_0.geometry}
            material={materials.blinn1}
            position={[2.48, 15.01, 1.36]}
            rotation={[0, 0, -1.19]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere88_blinn1_0.geometry}
            material={materials.blinn1}
            position={[2.82, 14.3, 1.93]}
            rotation={[0, 0, -1.19]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere89_blinn1_0.geometry}
            material={materials.blinn1}
            position={[2.48, 14.52, 1.42]}
            rotation={[0, 0, -1.19]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere90_blinn1_0.geometry}
            material={materials.blinn1}
            position={[2.48, 14.52, 1.42]}
            rotation={[0, 0, -1.19]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere91_blinn1_0.geometry}
            material={materials.blinn1}
            position={[2.82, 14.3, 1.93]}
            rotation={[0, 0, -1.19]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere92_blinn1_0.geometry}
            material={materials.blinn1}
            position={[2.48, 15.01, 1.36]}
            rotation={[0, 0, -1.19]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere93_blinn1_0.geometry}
            material={materials.blinn1}
            position={[16.14, -2.84, -11.53]}
            rotation={[0, 0.51, 0.17]}
          />
          <mesh
            geometry={nodes.pSphere94_blinn1_0.geometry}
            material={materials.blinn1}
            position={[12.51, -1.24, -3.86]}
            rotation={[-0.26, -0.24, 0.2]}
          />
          <mesh
            geometry={nodes.pSphere95_blinn1_0.geometry}
            material={materials.blinn1}
            position={[13.36, -0.27, 1.18]}
            rotation={[0, -0.86, 0.53]}
          />
          <mesh
            geometry={nodes.pSphere96_blinn1_0.geometry}
            material={materials.blinn1}
            position={[13.36, -0.27, 1.18]}
            rotation={[0, -0.86, 0.53]}
          />
          <mesh
            geometry={nodes.pSphere97_blinn1_0.geometry}
            material={materials.blinn1}
            position={[11.46, 14.96, -14.27]}
            rotation={[0, 0, 0.53]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere98_blinn1_0.geometry}
            material={materials.blinn1}
            position={[11.8, 14.25, -13.7]}
            rotation={[0, 0, 0.53]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere99_blinn1_0.geometry}
            material={materials.blinn1}
            position={[11.46, 14.47, -14.22]}
            rotation={[0, 0, 0.53]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere100_blinn1_0.geometry}
            material={materials.blinn1}
            position={[13.51, 15.45, -14.83]}
            rotation={[0, 0, 0.53]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere101_blinn1_0.geometry}
            material={materials.blinn1}
            position={[13.51, 15.45, -14.83]}
            rotation={[0, 0, 0.53]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere102_blinn1_0.geometry}
            material={materials.blinn1}
            position={[11.46, 14.47, -14.22]}
            rotation={[0, 0, 0.53]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere103_blinn1_0.geometry}
            material={materials.blinn1}
            position={[11.8, 14.25, -13.7]}
            rotation={[0, 0, 0.53]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere104_blinn1_0.geometry}
            material={materials.blinn1}
            position={[11.46, 14.96, -14.27]}
            rotation={[0, 0, 0.53]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere105_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-3.16, 23.07, -12.19]}
            rotation={[-1.15, 1.12, 1.21]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere106_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-2.82, 22.37, -11.62]}
            rotation={[-1.15, 1.12, 1.21]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere107_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-3.16, 22.58, -12.14]}
            rotation={[-1.15, 1.12, 1.21]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere108_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-1.11, 23.57, -12.75]}
            rotation={[-1.15, 1.12, 1.21]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere109_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-1.11, 23.57, -12.75]}
            rotation={[-1.15, 1.12, 1.21]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere110_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-3.16, 22.58, -12.14]}
            rotation={[-1.15, 1.12, 1.21]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere111_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-2.82, 22.37, -11.62]}
            rotation={[-1.15, 1.12, 1.21]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere112_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-3.16, 23.07, -12.19]}
            rotation={[-1.15, 1.12, 1.21]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere113_blinn1_0.geometry}
            material={materials.blinn1}
            position={[0.78, 7.43, 0.92]}
            rotation={[-0.47, 0.47, 0.32]}
          />
          <mesh
            geometry={nodes.pSphere114_blinn1_0.geometry}
            material={materials.blinn1}
            position={[0.78, 7.43, 0.92]}
            rotation={[-0.47, 0.47, 0.32]}
          />
          <mesh
            geometry={nodes.pSphere115_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-1.93, 5.82, -4.74]}
            rotation={[-0.49, 1.14, 0.24]}
          />
          <mesh
            geometry={nodes.pSphere116_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-0.47, 5.04, -11.87]}
            rotation={[-2.97, 1.24, 3]}
          />
          <mesh
            geometry={nodes.pSphere117_blinn1_0.geometry}
            material={materials.blinn1}
            position={[7.12, 23.07, -1.24]}
            rotation={[-1.15, 1.12, 0.47]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere118_blinn1_0.geometry}
            material={materials.blinn1}
            position={[7.46, 22.37, -0.67]}
            rotation={[-1.15, 1.12, 0.47]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere119_blinn1_0.geometry}
            material={materials.blinn1}
            position={[7.12, 22.58, -1.19]}
            rotation={[-1.15, 1.12, 0.47]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere120_blinn1_0.geometry}
            material={materials.blinn1}
            position={[9.17, 23.57, -1.8]}
            rotation={[-1.15, 1.12, 0.47]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere121_blinn1_0.geometry}
            material={materials.blinn1}
            position={[9.17, 23.57, -1.8]}
            rotation={[-1.15, 1.12, 0.47]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere122_blinn1_0.geometry}
            material={materials.blinn1}
            position={[7.12, 22.58, -1.19]}
            rotation={[-1.15, 1.12, 0.47]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere123_blinn1_0.geometry}
            material={materials.blinn1}
            position={[7.46, 22.37, -0.67]}
            rotation={[-1.15, 1.12, 0.47]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere124_blinn1_0.geometry}
            material={materials.blinn1}
            position={[7.12, 23.07, -1.24]}
            rotation={[-1.15, 1.12, 0.47]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere125_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-0.61, 10.02, 17.15]}
            rotation={[-0.47, 0.47, -0.42]}
          />
          <mesh
            geometry={nodes.pSphere126_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-0.61, 10.02, 17.15]}
            rotation={[-0.47, 0.47, -0.42]}
          />
          <mesh
            geometry={nodes.pSphere127_blinn1_0.geometry}
            material={materials.blinn1}
            position={[2.94, 12.23, 16.24]}
            rotation={[-0.49, 1.14, -0.5]}
          />
          <mesh
            geometry={nodes.pSphere128_blinn1_0.geometry}
            material={materials.blinn1}
            position={[13.63, 8.74, 11.02]}
            rotation={[-2.97, 1.24, 2.27]}
          />
          <mesh
            geometry={nodes.pSphere129_blinn1_0.geometry}
            material={materials.blinn1}
            position={[9.96, 13.45, 8.93]}
            rotation={[-1.39, 0.49, 0.39]}
          />
          <mesh
            geometry={nodes.pSphere130_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-5.73, 18, 10.83]}
            rotation={[-1.38, 0.2, -0.35]}
          />
          <mesh
            geometry={nodes.pSphere131_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-13.81, 13.51, 9.11]}
            rotation={[-1.32, -0.28, -0.83]}
          />
          <mesh
            geometry={nodes.pSphere132_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-13.81, 13.51, 9.11]}
            rotation={[-1.32, -0.28, -0.83]}
          />
          <mesh
            geometry={nodes.pSphere133_blinn1_0.geometry}
            material={materials.blinn1}
            position={[1.88, 18.21, -9.58]}
            rotation={[-1.2, 0, 0]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere134_blinn1_0.geometry}
            material={materials.blinn1}
            position={[2.22, 17.51, -9.01]}
            rotation={[-1.2, 0, 0]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere135_blinn1_0.geometry}
            material={materials.blinn1}
            position={[1.88, 17.72, -9.53]}
            rotation={[-1.2, 0, 0]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere136_blinn1_0.geometry}
            material={materials.blinn1}
            position={[3.93, 18.71, -10.14]}
            rotation={[-1.2, 0, 0]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere137_blinn1_0.geometry}
            material={materials.blinn1}
            position={[3.93, 18.71, -10.14]}
            rotation={[-1.2, 0, 0]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere138_blinn1_0.geometry}
            material={materials.blinn1}
            position={[1.88, 17.72, -9.53]}
            rotation={[-1.2, 0, 0]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere139_blinn1_0.geometry}
            material={materials.blinn1}
            position={[2.22, 17.51, -9.01]}
            rotation={[-1.2, 0, 0]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere140_blinn1_0.geometry}
            material={materials.blinn1}
            position={[1.88, 18.21, -9.58]}
            rotation={[-1.2, 0, 0]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere141_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-2.39, 23.04, 19.27]}
            rotation={[0, 0.51, -1.9]}
          />
          <mesh
            geometry={nodes.pSphere142_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-8.92, 21.72, 5.83]}
            rotation={[-0.26, -0.24, -1.87]}
          />
          <mesh
            geometry={nodes.pSphere143_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-4.71, 16.52, 0.29]}
            rotation={[0, -0.86, -1.54]}
          />
          <mesh
            geometry={nodes.pSphere144_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-4.71, 16.52, 0.29]}
            rotation={[0, -0.86, -1.54]}
          />
          <mesh
            geometry={nodes.pSphere145_blinn1_0.geometry}
            material={materials.blinn1}
            position={[11.68, 18.21, 6.14]}
            rotation={[0, 0, -1.54]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere146_blinn1_0.geometry}
            material={materials.blinn1}
            position={[12.01, 17.51, 6.7]}
            rotation={[0, 0, -1.54]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere147_blinn1_0.geometry}
            material={materials.blinn1}
            position={[11.68, 17.72, 6.19]}
            rotation={[0, 0, -1.54]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere148_blinn1_0.geometry}
            material={materials.blinn1}
            position={[13.73, 18.71, 5.58]}
            rotation={[0, 0, -1.54]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere149_blinn1_0.geometry}
            material={materials.blinn1}
            position={[13.73, 18.71, 5.58]}
            rotation={[0, 0, -1.54]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere150_blinn1_0.geometry}
            material={materials.blinn1}
            position={[11.68, 17.72, 6.19]}
            rotation={[0, 0, -1.54]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere151_blinn1_0.geometry}
            material={materials.blinn1}
            position={[12.01, 17.51, 6.7]}
            rotation={[0, 0, -1.54]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere152_blinn1_0.geometry}
            material={materials.blinn1}
            position={[11.68, 18.21, 6.14]}
            rotation={[0, 0, -1.54]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere153_blinn1_0.geometry}
            material={materials.blinn1}
            position={[15.9, 18.21, 1.48]}
            rotation={[-1.2, 0, -1.54]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere154_blinn1_0.geometry}
            material={materials.blinn1}
            position={[16.24, 17.51, 2.05]}
            rotation={[-1.2, 0, -1.54]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere155_blinn1_0.geometry}
            material={materials.blinn1}
            position={[15.9, 17.72, 1.54]}
            rotation={[-1.2, 0, -1.54]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere156_blinn1_0.geometry}
            material={materials.blinn1}
            position={[17.95, 18.71, 0.92]}
            rotation={[-1.2, 0, -1.54]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere157_blinn1_0.geometry}
            material={materials.blinn1}
            position={[17.95, 18.71, 0.92]}
            rotation={[-1.2, 0, -1.54]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere158_blinn1_0.geometry}
            material={materials.blinn1}
            position={[15.9, 17.72, 1.54]}
            rotation={[-1.2, 0, -1.54]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere159_blinn1_0.geometry}
            material={materials.blinn1}
            position={[16.24, 17.51, 2.05]}
            rotation={[-1.2, 0, -1.54]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere160_blinn1_0.geometry}
            material={materials.blinn1}
            position={[15.9, 18.21, 1.48]}
            rotation={[-1.2, 0, -1.54]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere161_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-0.54, 19.57, -4.31]}
            rotation={[-1.32, -0.28, -2.37]}
          />
          <mesh
            geometry={nodes.pSphere162_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-0.54, 19.57, -4.31]}
            rotation={[-1.32, -0.28, -2.37]}
          />
          <mesh
            geometry={nodes.pSphere163_blinn1_0.geometry}
            material={materials.blinn1}
            position={[2.82, 25.9, 14.16]}
            rotation={[-1.39, 0.49, -1.15]}
          />
          <mesh
            geometry={nodes.pSphere164_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-3.76, 24.59, 0.73]}
            rotation={[-1.38, 0.2, -1.89]}
          />
          <mesh
            geometry={nodes.pSphere165_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-9.16, 29.9, 6.56]}
            rotation={[-1.38, 0.2, -1.89]}
          />
          <mesh
            geometry={nodes.pSphere166_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-2.58, 31.21, 19.99]}
            rotation={[-1.39, 0.49, -1.15]}
          />
          <mesh
            geometry={nodes.pSphere167_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-5.94, 24.88, 1.52]}
            rotation={[-1.32, -0.28, -2.37]}
          />
          <mesh
            geometry={nodes.pSphere168_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-5.94, 24.88, 1.52]}
            rotation={[-1.32, -0.28, -2.37]}
          />
          <mesh
            geometry={nodes.pSphere169_blinn1_0.geometry}
            material={materials.blinn1}
            position={[10.51, 23.52, 7.32]}
            rotation={[-1.2, 0, -1.54]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere170_blinn1_0.geometry}
            material={materials.blinn1}
            position={[10.84, 22.82, 7.89]}
            rotation={[-1.2, 0, -1.54]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere171_blinn1_0.geometry}
            material={materials.blinn1}
            position={[10.51, 23.03, 7.37]}
            rotation={[-1.2, 0, -1.54]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere172_blinn1_0.geometry}
            material={materials.blinn1}
            position={[10.51, 23.03, 7.37]}
            rotation={[-1.2, 0, -1.54]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere173_blinn1_0.geometry}
            material={materials.blinn1}
            position={[10.84, 22.82, 7.89]}
            rotation={[-1.2, 0, -1.54]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere174_blinn1_0.geometry}
            material={materials.blinn1}
            position={[10.51, 23.52, 7.32]}
            rotation={[-1.2, 0, -1.54]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere175_blinn1_0.geometry}
            material={materials.blinn1}
            position={[8.33, 24.02, 11.41]}
            rotation={[0, 0, -1.54]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere176_blinn1_0.geometry}
            material={materials.blinn1}
            position={[8.33, 24.02, 11.41]}
            rotation={[0, 0, -1.54]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere177_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-4.08, 22.55, -7.94]}
            rotation={[-1.88, 0.33, -1.75]}
          />
          <mesh
            geometry={nodes.pSphere178_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-0.52, 17.82, -12.6]}
            rotation={[-1.66, 0.08, -2.4]}
          />
          <mesh
            geometry={nodes.pSphere179_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-0.52, 17.82, -12.6]}
            rotation={[-1.66, 0.08, -2.4]}
          />
          <mesh
            geometry={nodes.pSphere180_blinn1_0.geometry}
            material={materials.blinn1}
            position={[10.96, 15.82, -1.46]}
            rotation={[-0.5, -0.01, -1.54]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere181_blinn1_0.geometry}
            material={materials.blinn1}
            position={[11.3, 15.12, -0.89]}
            rotation={[-0.5, -0.01, -1.54]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere182_blinn1_0.geometry}
            material={materials.blinn1}
            position={[13.01, 16.32, -2.02]}
            rotation={[-0.5, -0.01, -1.54]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere183_blinn1_0.geometry}
            material={materials.blinn1}
            position={[10.96, 15.34, -1.41]}
            rotation={[-0.5, -0.01, -1.54]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere184_blinn1_0.geometry}
            material={materials.blinn1}
            position={[10.96, 15.82, -1.46]}
            rotation={[-0.5, -0.01, -1.54]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere185_blinn1_0.geometry}
            material={materials.blinn1}
            position={[13.01, 16.32, -2.02]}
            rotation={[-0.5, -0.01, -1.54]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere186_blinn1_0.geometry}
            material={materials.blinn1}
            position={[10.96, 15.34, -1.41]}
            rotation={[-0.5, -0.01, -1.54]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere187_blinn1_0.geometry}
            material={materials.blinn1}
            position={[11.3, 15.12, -0.89]}
            rotation={[-0.5, -0.01, -1.54]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere188_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-11.18, 9.11, -8.34]}
            rotation={[0.95, -0.03, -0.61]}
          />
          <mesh
            geometry={nodes.pSphere189_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-3.63, 5.55, -8.51]}
            rotation={[0.84, -0.4, 0.05]}
          />
          <mesh
            geometry={nodes.pSphere190_blinn1_0.geometry}
            material={materials.blinn1}
            position={[7.13, 8.76, -2.05]}
            rotation={[1.21, -0.39, 0.79]}
          />
          <mesh
            geometry={nodes.pSphere191_blinn1_0.geometry}
            material={materials.blinn1}
            position={[7.13, 8.76, -2.05]}
            rotation={[1.21, -0.39, 0.79]}
          />
          <mesh
            geometry={nodes.pSphere192_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-1.66, 19.79, 0.26]}
            rotation={[1.05, 0, 0]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere193_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-1.32, 19.09, 0.83]}
            rotation={[1.05, 0, 0]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere194_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-1.66, 19.31, 0.31]}
            rotation={[1.05, 0, 0]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere195_blinn1_0.geometry}
            material={materials.blinn1}
            position={[0.39, 20.29, -0.3]}
            rotation={[1.05, 0, 0]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere196_blinn1_0.geometry}
            material={materials.blinn1}
            position={[0.39, 20.29, -0.3]}
            rotation={[1.05, 0, 0]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere197_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-1.66, 19.31, 0.31]}
            rotation={[1.05, 0, 0]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere198_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-1.32, 19.09, 0.83]}
            rotation={[1.05, 0, 0]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere199_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-1.66, 19.79, 0.26]}
            rotation={[1.05, 0, 0]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere200_blinn1_0.geometry}
            material={materials.blinn1}
            position={[2.57, 19.79, -4.39]}
            rotation={[-0.15, 0, 0]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere201_blinn1_0.geometry}
            material={materials.blinn1}
            position={[2.9, 19.09, -3.83]}
            rotation={[-0.15, 0, 0]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere202_blinn1_0.geometry}
            material={materials.blinn1}
            position={[2.57, 19.31, -4.34]}
            rotation={[-0.15, 0, 0]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere203_blinn1_0.geometry}
            material={materials.blinn1}
            position={[4.61, 20.29, -4.95]}
            rotation={[-0.15, 0, 0]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere204_blinn1_0.geometry}
            material={materials.blinn1}
            position={[4.61, 20.29, -4.95]}
            rotation={[-0.15, 0, 0]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere205_blinn1_0.geometry}
            material={materials.blinn1}
            position={[2.57, 19.31, -4.34]}
            rotation={[-0.15, 0, 0]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere206_blinn1_0.geometry}
            material={materials.blinn1}
            position={[2.9, 19.09, -3.83]}
            rotation={[-0.15, 0, 0]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere207_blinn1_0.geometry}
            material={materials.blinn1}
            position={[2.57, 19.79, -4.39]}
            rotation={[-0.15, 0, 0]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere208_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-3.38, 2.1, 5.94]}
            rotation={[-0.22, -0.85, -0.17]}
          />
          <mesh
            geometry={nodes.pSphere209_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-3.38, 2.1, 5.94]}
            rotation={[-0.22, -0.85, -0.17]}
          />
          <mesh
            geometry={nodes.pSphere210_blinn1_0.geometry}
            material={materials.blinn1}
            position={[0.39, 2.89, 5.14]}
            rotation={[-0.16, 0.55, -0.28]}
          />
          <mesh
            geometry={nodes.pSphere211_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-6.06, 4.2, 6.21]}
            rotation={[-0.4, -0.19, -0.36]}
          />
          <mesh
            geometry={nodes.pSphere233_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-1.75, -0.35, 0.46]}
            rotation={[-0.01, -0.43, -0.07]}
          />
          <mesh
            geometry={nodes.pSphere234_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-3.59, 7.93, -15.35]}
            rotation={[0, 0.51, 1.02]}
          />
          <mesh
            geometry={nodes.pSphere235_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-6.4, 10.35, -1.69]}
            rotation={[-0.26, -0.24, 1.06]}
          />
          <mesh
            geometry={nodes.pSphere236_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-11.68, 14.17, 9.24]}
            rotation={[0, -0.86, 1.39]}
          />
          <mesh
            geometry={nodes.pSphere237_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-11.68, 14.17, 9.24]}
            rotation={[0, -0.86, 1.39]}
          />
          <mesh
            geometry={nodes.pSphere238_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-18.77, 16.57, -12.27]}
            rotation={[0, 0, 1.39]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere239_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-18.43, 15.87, -11.7]}
            rotation={[0, 0, 1.39]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere240_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-18.77, 16.08, -12.22]}
            rotation={[0, 0, 1.39]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere241_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-18.77, 16.08, -12.22]}
            rotation={[0, 0, 1.39]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere242_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-18.43, 15.87, -11.7]}
            rotation={[0, 0, 1.39]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere243_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-18.77, 16.57, -12.27]}
            rotation={[0, 0, 1.39]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere244_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-8.02, 17.67, 5.07]}
            rotation={[-1.32, -0.28, 0.56]}
          />
          <mesh
            geometry={nodes.pSphere245_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-8.02, 17.67, 5.07]}
            rotation={[-1.32, -0.28, 0.56]}
          />
          <mesh
            geometry={nodes.pSphere246_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-1.26, 13.81, -6.25]}
            rotation={[-1.38, 0.2, 1.04]}
          />
          <mesh
            geometry={nodes.pSphere247_blinn1_0.geometry}
            material={materials.blinn1}
            position={[11.46, 9.44, -13.91]}
            rotation={[-0.68, -0.38, 0.59]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere248_blinn1_0.geometry}
            material={materials.blinn1}
            position={[11.8, 8.74, -13.35]}
            rotation={[-0.68, -0.38, 0.59]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere249_blinn1_0.geometry}
            material={materials.blinn1}
            position={[11.46, 8.95, -13.86]}
            rotation={[-0.68, -0.38, 0.59]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere250_blinn1_0.geometry}
            material={materials.blinn1}
            position={[13.51, 9.94, -14.47]}
            rotation={[-0.68, -0.38, 0.59]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere251_blinn1_0.geometry}
            material={materials.blinn1}
            position={[13.51, 9.94, -14.47]}
            rotation={[-0.68, -0.38, 0.59]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere252_blinn1_0.geometry}
            material={materials.blinn1}
            position={[11.46, 8.95, -13.86]}
            rotation={[-0.68, -0.38, 0.59]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere253_blinn1_0.geometry}
            material={materials.blinn1}
            position={[11.8, 8.74, -13.35]}
            rotation={[-0.68, -0.38, 0.59]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere254_blinn1_0.geometry}
            material={materials.blinn1}
            position={[11.46, 9.44, -13.91]}
            rotation={[-0.68, -0.38, 0.59]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere255_blinn1_0.geometry}
            material={materials.blinn1}
            position={[4.04, 1.87, 8.57]}
            rotation={[-1.26, -0.91, -0.3]}
          />
          <mesh
            geometry={nodes.pSphere256_blinn1_0.geometry}
            material={materials.blinn1}
            position={[4.04, 1.87, 8.57]}
            rotation={[-1.26, -0.91, -0.3]}
          />
          <mesh
            geometry={nodes.pSphere257_blinn1_0.geometry}
            material={materials.blinn1}
            position={[11.46, 3.51, 5.89]}
            rotation={[-1.05, -0.34, 0.16]}
          />
          <mesh
            geometry={nodes.pSphere258_blinn1_0.geometry}
            material={materials.blinn1}
            position={[23.56, -0.94, -1.97]}
            rotation={[-0.77, 0.23, 0.65]}
          />
          <mesh
            geometry={nodes.pSphere259_blinn1_0.geometry}
            material={materials.blinn1}
            position={[4.5, 0.68, 10.28]}
            rotation={[-0.89, 0.57, 0.32]}
          />
          <mesh
            geometry={nodes.pSphere260_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-8.12, 4.6, 14.36]}
            rotation={[-0.99, 0.02, -0.21]}
          />
          <mesh
            geometry={nodes.pSphere261_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-13.04, 1.46, 14.09]}
            rotation={[-0.99, -0.6, -0.51]}
          />
          <mesh
            geometry={nodes.pSphere262_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-13.04, 1.46, 14.09]}
            rotation={[-0.99, -0.6, -0.51]}
          />
          <mesh
            geometry={nodes.pSphere263_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-2.34, 12.7, -4.57]}
            rotation={[-0.76, -0.03, 0.18]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere264_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-2.01, 11.99, -4]}
            rotation={[-0.76, -0.03, 0.18]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere265_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-2.34, 12.21, -4.52]}
            rotation={[-0.76, -0.03, 0.18]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere266_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-0.29, 13.19, -5.13]}
            rotation={[-0.76, -0.03, 0.18]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere267_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-0.29, 13.19, -5.13]}
            rotation={[-0.76, -0.03, 0.18]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere268_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-2.34, 12.21, -4.52]}
            rotation={[-0.76, -0.03, 0.18]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere269_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-2.01, 11.99, -4]}
            rotation={[-0.76, -0.03, 0.18]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere270_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-2.34, 12.7, -4.57]}
            rotation={[-0.76, -0.03, 0.18]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere271_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-5.52, -3.99, 5.07]}
            rotation={[0.02, -0.35, -0.07]}
          />
          <mesh
            geometry={nodes.pSphere272_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-9.26, 5.18, 15.59]}
            rotation={[-1.12, -0.51, -0.57]}
          />
          <mesh
            geometry={nodes.pSphere273_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-9.26, 5.18, 15.59]}
            rotation={[-1.12, -0.51, -0.57]}
          />
          <mesh
            geometry={nodes.pSphere274_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-1.66, 13.79, 0.67]}
            rotation={[0.29, -0.03, 0.18]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere275_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-1.32, 13.58, 1.19]}
            rotation={[0.29, -0.03, 0.18]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere276_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-1.66, 14.28, 0.62]}
            rotation={[0.29, -0.03, 0.18]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere277_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-1.66, 14.28, 0.62]}
            rotation={[0.29, -0.03, 0.18]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere278_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-1.32, 13.58, 1.19]}
            rotation={[0.29, -0.03, 0.18]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere279_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-1.66, 13.79, 0.67]}
            rotation={[0.29, -0.03, 0.18]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere280_blinn1_0.geometry}
            material={materials.blinn1}
            position={[2.22, 11.99, -8.66]}
            rotation={[-1.96, -0.03, 0.18]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere281_blinn1_0.geometry}
            material={materials.blinn1}
            position={[2.22, 11.99, -8.66]}
            rotation={[-1.96, -0.03, 0.18]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere282_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-10.02, 21.39, 10.47]}
            rotation={[-1.85, 0.27, -0.63]}
          />
          <mesh
            geometry={nodes.pSphere283_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-10.02, 21.39, 10.47]}
            rotation={[-1.85, 0.27, -0.63]}
          />
          <mesh
            geometry={nodes.pSphere284_blinn1_0.geometry}
            material={materials.blinn1}
            position={[15.69, 19.31, 3.59]}
            rotation={[-2.07, 0.08, 0.79]}
          />
          <mesh
            geometry={nodes.pSphere285_blinn1_0.geometry}
            material={materials.blinn1}
            position={[1.93, 23.63, 7.76]}
            rotation={[-2.16, 0.36, 0.08]}
          />
          <mesh
            geometry={nodes.pSphere286_blinn1_0.geometry}
            material={materials.blinn1}
            position={[17.8, 9.44, -13.91]}
            rotation={[-1.96, -0.68, -0.14]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere287_blinn1_0.geometry}
            material={materials.blinn1}
            position={[18.14, 8.74, -13.35]}
            rotation={[-1.96, -0.68, -0.14]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere288_blinn1_0.geometry}
            material={materials.blinn1}
            position={[17.8, 8.95, -13.86]}
            rotation={[-1.96, -0.68, -0.14]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere289_blinn1_0.geometry}
            material={materials.blinn1}
            position={[19.85, 9.94, -14.47]}
            rotation={[-1.96, -0.68, -0.14]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere290_blinn1_0.geometry}
            material={materials.blinn1}
            position={[19.85, 9.94, -14.47]}
            rotation={[-1.96, -0.68, -0.14]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere291_blinn1_0.geometry}
            material={materials.blinn1}
            position={[17.8, 8.95, -13.86]}
            rotation={[-1.96, -0.68, -0.14]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere292_blinn1_0.geometry}
            material={materials.blinn1}
            position={[18.14, 8.74, -13.35]}
            rotation={[-1.96, -0.68, -0.14]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere293_blinn1_0.geometry}
            material={materials.blinn1}
            position={[17.8, 9.44, -13.91]}
            rotation={[-1.96, -0.68, -0.14]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere294_blinn1_0.geometry}
            material={materials.blinn1}
            position={[0.71, 16.86, 1.3]}
            rotation={[-2.32, -0.19, -0.94]}
          />
          <mesh
            geometry={nodes.pSphere295_blinn1_0.geometry}
            material={materials.blinn1}
            position={[0.71, 16.86, 1.3]}
            rotation={[-2.32, -0.19, -0.94]}
          />
          <mesh
            geometry={nodes.pSphere296_blinn1_0.geometry}
            material={materials.blinn1}
            position={[10.97, 21.14, 2.22]}
            rotation={[-2.23, -0.29, -0.24]}
          />
          <mesh
            geometry={nodes.pSphere297_blinn1_0.geometry}
            material={materials.blinn1}
            position={[26.17, 17.27, 3.07]}
            rotation={[-1.68, -0.44, 0.54]}
          />
          <mesh
            geometry={nodes.pSphere298_blinn1_0.geometry}
            material={materials.blinn1}
            position={[15.83, 19.29, 10.49]}
            rotation={[-1.92, 0.01, 0.64]}
          />
          <mesh
            geometry={nodes.pSphere299_blinn1_0.geometry}
            material={materials.blinn1}
            position={[1.07, 23.59, 12.76]}
            rotation={[-2.09, 0.2, -0.08]}
          />
          <mesh
            geometry={nodes.pSphere300_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-10.39, 20.37, 13.79]}
            rotation={[-1.9, 0.11, -0.76]}
          />
          <mesh
            geometry={nodes.pSphere301_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-10.39, 20.37, 13.79]}
            rotation={[-1.9, 0.11, -0.76]}
          />
          <mesh
            geometry={nodes.pSphere302_blinn1_0.geometry}
            material={materials.blinn1}
            position={[4, 12.7, -4.57]}
            rotation={[-1.87, -0.18, 0.06]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere303_blinn1_0.geometry}
            material={materials.blinn1}
            position={[4.34, 11.99, -4]}
            rotation={[-1.87, -0.18, 0.06]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere304_blinn1_0.geometry}
            material={materials.blinn1}
            position={[4, 12.21, -4.52]}
            rotation={[-1.87, -0.18, 0.06]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere305_blinn1_0.geometry}
            material={materials.blinn1}
            position={[6.05, 13.19, -5.13]}
            rotation={[-1.87, -0.18, 0.06]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere306_blinn1_0.geometry}
            material={materials.blinn1}
            position={[6.05, 13.19, -5.13]}
            rotation={[-1.87, -0.18, 0.06]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere307_blinn1_0.geometry}
            material={materials.blinn1}
            position={[4, 12.21, -4.52]}
            rotation={[-1.87, -0.18, 0.06]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere308_blinn1_0.geometry}
            material={materials.blinn1}
            position={[4.34, 11.99, -4]}
            rotation={[-1.87, -0.18, 0.06]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere309_blinn1_0.geometry}
            material={materials.blinn1}
            position={[4, 12.7, -4.57]}
            rotation={[-1.87, -0.18, 0.06]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere310_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-3.54, 7.82, 19.66]}
            rotation={[-1.1, -0.1, -0.34]}
          />
          <mesh
            geometry={nodes.pSphere311_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-4.49, 24.27, 13.47]}
            rotation={[-2.01, 0.21, -0.72]}
          />
          <mesh
            geometry={nodes.pSphere312_blinn1_0.geometry}
            material={materials.blinn1}
            position={[-4.49, 24.27, 13.47]}
            rotation={[-2.01, 0.21, -0.72]}
          />
          <mesh
            geometry={nodes.pSphere313_blinn1_0.geometry}
            material={materials.blinn1}
            position={[4.69, 13.79, 0.67]}
            rotation={[-0.82, -0.18, 0.06]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere314_blinn1_0.geometry}
            material={materials.blinn1}
            position={[5.02, 13.58, 1.19]}
            rotation={[-0.82, -0.18, 0.06]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere315_blinn1_0.geometry}
            material={materials.blinn1}
            position={[4.69, 14.28, 0.62]}
            rotation={[-0.82, -0.18, 0.06]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere316_blinn1_0.geometry}
            material={materials.blinn1}
            position={[4.69, 14.28, 0.62]}
            rotation={[-0.82, -0.18, 0.06]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere317_blinn1_0.geometry}
            material={materials.blinn1}
            position={[5.02, 13.58, 1.19]}
            rotation={[-0.82, -0.18, 0.06]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere318_blinn1_0.geometry}
            material={materials.blinn1}
            position={[4.69, 13.79, 0.67]}
            rotation={[-0.82, -0.18, 0.06]}
            scale={[0.04, 0.03, 0.03]}
          />
          <mesh
            geometry={nodes.pSphere319_blinn1_0.geometry}
            material={materials.blinn1}
            position={[8.56, 11.99, -8.66]}
            rotation={[-3.07, -0.18, 0.06]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere320_blinn1_0.geometry}
            material={materials.blinn1}
            position={[8.56, 11.99, -8.66]}
            rotation={[-3.07, -0.18, 0.06]}
            scale={0.06}
          />
          <mesh
            geometry={nodes.pSphere321_blinn1_0.geometry}
            material={materials.blinn1}
            position={[7.23, 30.74, -2.36]}
            rotation={[-3.05, 0.68, -0.02]}
          />
          <mesh
            geometry={nodes.pSphere322_blinn1_0.geometry}
            material={materials.blinn1}
            position={[7.23, 30.74, -2.36]}
            rotation={[-3.05, 0.68, -0.02]}
          />
          <mesh
            geometry={nodes.pSphere323_blinn1_0.geometry}
            material={materials.blinn1}
            position={[14.72, 28.99, -11.39]}
            rotation={[-2.98, -0.64, 0.5]}
          />
          <mesh
            geometry={nodes.pSphere324_blinn1_0.geometry}
            material={materials.blinn1}
            position={[12.68, 28.85, -10.25]}
            rotation={[3.01, 0.09, 0.35]}
          />
        </group>
      </group>
    </group>
  );
};

useGLTF.preload(TreeHousesModel);
export default TreeHouses;
