/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 -T src/worlds/Gemsoria/assets/Cavern.glb
Author: salinaforr (https://sketchfab.com/salinaforr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-cave-of-eternity-db7952f26213449ea35a7f6099b91005
Title: The Cave of Eternity
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import CavernModel from '../assets/Cavern.glb';

export function Cavern(props) {
  const { nodes, materials } = useGLTF(CavernModel);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.FinalpolySurface13_fonar_0.geometry}
        material={materials.fonar}
      />
      <mesh
        geometry={nodes.FinalpPlane7_listva_0.geometry}
        material={materials.listva}
      />
      <mesh
        geometry={nodes.FinalpolySurface6polySurface13_Default_0.geometry}
        material={materials.Default}
      />
      <mesh
        geometry={nodes.FinalpolySurface14polySurface6_Default_0.geometry}
        material={materials.Default}
      />
      <mesh
        geometry={nodes.FinalpolySurface6polySurface15_Default_0.geometry}
        material={materials.Default}
      />
      <mesh
        geometry={nodes.FinalpolySurface6polySurface12_Default_0.geometry}
        material={materials.Default}
      />
      <mesh
        geometry={nodes.FinalpolySurface5polySurface11_Default_0.geometry}
        material={materials.Default}
      />
      <mesh
        geometry={nodes.FinalpPlane9_listva_0.geometry}
        material={materials.listva}
      />
      <mesh
        geometry={nodes.FinalpolySurface25_portal_0.geometry}
        material={materials.portal}
      />
      <mesh
        geometry={nodes.FinalpPlane13_listva_0.geometry}
        material={materials.listva}
      />
      <mesh
        geometry={nodes.FinalpPlane10_listva_0.geometry}
        material={materials.listva}
      />
      <mesh
        geometry={nodes['FinalpolySurface42_portal_(1)_(1)_(1)_(1)_0'].geometry}
        material={materials.portal_1_1_1_1}
      />
      <mesh
        geometry={nodes.FinalpolySurface1polySurface130_octrovki_0.geometry}
        material={materials.octrovki}
      />
      <mesh
        geometry={nodes.FinalpPlane16_liana_0.geometry}
        material={materials.liana}
      />
      <mesh
        geometry={nodes.FinalpolySurface5polySurface10_voda_0.geometry}
        material={materials.voda}
      />
      <mesh
        geometry={nodes.FinalpolySurface5_Default_0.geometry}
        material={materials.Default_4}
      />
      <mesh
        geometry={nodes.FinalpolySurface5polySurface9_Default_0.geometry}
        material={materials.voda}
      />
      <mesh
        geometry={nodes.FinalpPlane11_listva_0.geometry}
        material={materials.listva}
      />
      <mesh
        geometry={nodes.FinalpPlane13polySurface8_Default_0.geometry}
        material={materials.Default_6}
      />
      <mesh
        geometry={nodes.FinalpolySurface6polySurface16_Default_0.geometry}
        material={materials.Default}
      />
      <mesh
        geometry={nodes.FinalpolySurface6polySurface17_Default_0.geometry}
        material={materials.Default}
      />
      <mesh
        geometry={nodes.FinalpCube1_fonar_0.geometry}
        material={materials.fonar_0}
      />
      <mesh
        geometry={nodes.FinalpPlane8_listva_0.geometry}
        material={materials.listva}
      />
      <mesh
        geometry={nodes.FinalpPlane6_listva_0.geometry}
        material={materials.listva}
      />
      <mesh
        geometry={nodes.FinalpolySurface1_derevo_0.geometry}
        material={materials.derevo}
      />
      <mesh
        geometry={nodes.polySurface28_FinalpolySurface4_Default_0.geometry}
        material={materials.Default_9}
      />
      <mesh
        geometry={nodes.FinalpolySurface4_polySurface27_Default_0.geometry}
        material={materials.Default_9}
      />
      <mesh
        geometry={nodes.FinalpPlane31_Default_0.geometry}
        material={materials.Default_11}
      />
      <mesh
        geometry={nodes.FinalpPlane32_liana_0.geometry}
        material={materials.liana_0}
        position={[0, 0, -4.53]}
      />
      <mesh
        geometry={nodes['FinalpolySurface3_portal_(1)_0'].geometry}
        material={materials.portal_1}
      />
      <mesh
        geometry={nodes.FinalLodka_lodka_0.geometry}
        material={materials.lodka}
        position={[0, 0.07, 0]}
      />
      <mesh
        geometry={nodes['FinalpolySurface43_portal_(1)_(1)_(1)_0'].geometry}
        material={materials.portal_1_1_1}
      />
      <mesh
        geometry={nodes.FinalpPlane33_liana_0.geometry}
        material={materials.liana_1}
        position={[0, 0, 3.88]}
      />
      <mesh
        geometry={nodes.FinalpolySurface51_doroga_0.geometry}
        material={materials.doroga}
      />
      <mesh
        geometry={nodes.FinalpolySurface50_altar_0.geometry}
        material={materials.altar}
      />
      <mesh
        geometry={nodes['FinalpolySurface49_portal_(1)_(1)_0'].geometry}
        material={materials.portal_1_1}
      />
      <mesh
        geometry={nodes.FinalpolySurface6_NewMat01_0.geometry}
        material={materials.NewMat01}
      />
      <mesh
        geometry={nodes.FinalpPlane12_listva_0.geometry}
        material={materials.listva}
      />
      <mesh
        geometry={nodes.FinalpPlane14_listva_0.geometry}
        material={materials.listva}
      />
      <mesh
        geometry={nodes.FinalpolySurface48_altar_0.geometry}
        material={materials.altar_0}
      />
      <mesh
        geometry={nodes.FinalpPlane22_liana_0.geometry}
        material={materials.liana}
      />
      <mesh
        geometry={nodes.FinalpPlane5_listva_0.geometry}
        material={materials.listva}
      />
      <mesh
        geometry={nodes.FinalpPlane34_zvezda_0.geometry}
        material={materials.zvezda}
        position={[0, 19.78, 0]}
        rotation={[0, 0.46, 0]}
      />
      <mesh
        geometry={nodes.polySurface30_Default_0.geometry}
        material={materials.Default_12}
      />
      <mesh
        geometry={nodes.polySurface30_kamni_0.geometry}
        material={materials.kamni}
      />
      <mesh
        geometry={nodes.polySurface6_Default_0.geometry}
        material={materials.Default_13}
      />
      <mesh
        geometry={nodes.FinalpolySurface5polySurface43_Default_0.geometry}
        material={materials.Default_14}
      />
    </group>
  );
}

useGLTF.preload(CavernModel);
